name: Release

on:
  release:
    types: [ published ]

jobs:
  publish:
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Release Gem
      uses: virtualstaticvoid/publish-rubygems-action@v3
      env:
        GIT_NAME: "Chris Stefano"
        GIT_EMAIL: "virtualstaticvoid@gmail.com"
        RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
